name: Deploy to Cloudflare Workers

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            HERE_API_KEY
            SENTRY_DSN
        env:
          HERE_API_KEY: ${{ secrets.HERE_API_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Post-deployment health check
        run: |
          sleep 10
          curl -f https://ww-proxy.YOUR_SUBDOMAIN.workers.dev/health || exit 1
